// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4sdCgzcYocAYQezBsVpiBnEISQ3uQyeY',
    appId: '1:43305267188:web:65c9c4e0b1323a5a1fd3a1',
    messagingSenderId: '43305267188',
    projectId: 'nips-a001d',
    authDomain: 'nips-a001d.firebaseapp.com',
    storageBucket: 'nips-a001d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5eWM2frxtmFUeMvtyc_Udz50UnSL97KE',
    appId: '1:43305267188:android:fcdce27ae730388e1fd3a1',
    messagingSenderId: '43305267188',
    projectId: 'nips-a001d',
    storageBucket: 'nips-a001d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNT_yamnFDT7OqALh8ZA7AMU42ibzzz04',
    appId: '1:43305267188:ios:8971d6155b10d9671fd3a1',
    messagingSenderId: '43305267188',
    projectId: 'nips-a001d',
    storageBucket: 'nips-a001d.firebasestorage.app',
    iosBundleId: 'com.example.nipss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNT_yamnFDT7OqALh8ZA7AMU42ibzzz04',
    appId: '1:43305267188:ios:8971d6155b10d9671fd3a1',
    messagingSenderId: '43305267188',
    projectId: 'nips-a001d',
    storageBucket: 'nips-a001d.firebasestorage.app',
    iosBundleId: 'com.example.nipss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4sdCgzcYocAYQezBsVpiBnEISQ3uQyeY',
    appId: '1:43305267188:web:94cda4970fbef65a1fd3a1',
    messagingSenderId: '43305267188',
    projectId: 'nips-a001d',
    authDomain: 'nips-a001d.firebaseapp.com',
    storageBucket: 'nips-a001d.firebasestorage.app',
  );
}
